In [46]:
import numpy as np
np.random.seed(42)

In [47]:
print("1. Creating Temperature Data Array")
print("-" * 70)

daily_temps = np.random.uniform(-10, 40, (365, 5))

print(f"Array Shape: {daily_temps.shape}")
print(f"Number of Dimensions: {daily_temps.ndim}")
print(f"Data Type: {daily_temps.dtype}")
print(f"Total Elements: {daily_temps.size}")
print(f"\nSample data (first 3 days for all cities):")
print(daily_temps[:3, :])


1. Creating Temperature Data Array
----------------------------------------------------------------------
Array Shape: (365, 5)
Number of Dimensions: 2
Data Type: float64
Total Elements: 1825

Sample data (first 3 days for all cities):
[[ 8.72700594 37.53571532 26.59969709 19.93292421 -2.19906798]
 [-2.20027398 -7.09581939 33.30880729 20.05575059 25.40362889]
 [-8.97077529 38.49549261 31.62213204  0.61695553 -0.90875164]]


In [48]:
print("\n2. Creating Sales Matrix")
print("-" * 70)

monthly_sales = np.random.randint(1000, 5001, (12, 4))
print(f"Sales Matrix Shape: {monthly_sales.shape}")
print(f"Sales Data:\n{monthly_sales}")



2. Creating Sales Matrix
----------------------------------------------------------------------
Sales Matrix Shape: (12, 4)
Sales Data:
[[1377 1118 1189 3814]
 [1369 2801 3196 4747]
 [1651 2882 2511 1769]
 [3421 1780 2716 3207]
 [3398 4983 2311 4359]
 [3939 2249 1522 1521]
 [1782 3320 1935 4473]
 [3230 2688 1487 2850]
 [1845 3171 4032 4697]
 [3837 3461 3003 2748]
 [4243 4359 4506 1685]
 [3160 3935 4988 3169]]


In [75]:
print("\n3. Special Arrays")
print("-" * 70)

identity_5x5 = np.eye(5)
print("Identity Matrix (5x5):")
print(identity_5x5)

linear_space = np.linspace(0, 100, 50)
print(f"\nLinear Space Array (50 values from 0 to 100):")
print(f"First 5 values: {linear_space[:5]}")
print(f"Last 5 values: {linear_space[-5:]}")



3. Special Arrays
----------------------------------------------------------------------
Identity Matrix (5x5):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]

Linear Space Array (50 values from 0 to 100):
First 5 values: [0.         2.04081633 4.08163265 6.12244898 8.16326531]
Last 5 values: [ 91.83673469  93.87755102  95.91836735  97.95918367 100.        ]


In [51]:
print("\n1. Basic Slicing")
print("-" * 70)

january_temps = daily_temps[:31, :]
print(f"January data shape: {january_temps.shape}")
print(f"January average per city: {january_temps.mean(axis=0)}")



1. Basic Slicing
----------------------------------------------------------------------
January data shape: (31, 5)
January average per city: [15.45566362 13.07501578 13.89404635 12.69813444 13.74955282]


In [52]:
summer_temps = daily_temps[151:243, :]
print(f"\nSummer months data shape: {summer_temps.shape}")
print(f"Summer average per city: {summer_temps.mean(axis=0)}")



Summer months data shape: (92, 5)
Summer average per city: [15.54255674 16.61975996 14.52594548 16.20939938 13.81648226]


In [53]:
weekend_temps = daily_temps[4::7, :]
print(f"\nWeekend data shape: {weekend_temps.shape}")
print(f"Weekend average per city: {weekend_temps.mean(axis=0)}")



Weekend data shape: (52, 5)
Weekend average per city: [16.31336103 13.98207445 14.15843416 15.68937433 14.25728992]


In [54]:
print("\n2. Boolean Indexing")
print("-" * 70)

hot_days_mask = np.any(daily_temps > 35, axis=1)
hot_days_count = np.sum(hot_days_mask)
print(f"Days with temperature > 35°C in any city: {hot_days_count}")
print(f"Day indices (first 10): {np.where(hot_days_mask)[0][:10]}")



2. Boolean Indexing
----------------------------------------------------------------------
Days with temperature > 35°C in any city: 144
Day indices (first 10): [ 0  2  6  8 10 11 13 20 22 26]


In [55]:
freezing_days_per_city = np.sum(daily_temps < 0, axis=0)
print(f"\nFreezing days (< 0°C) per city:")
for idx, count in enumerate(freezing_days_per_city):
    print(f"  City {idx+1}: {count} days")



Freezing days (< 0°C) per city:
  City 1: 81 days
  City 2: 75 days
  City 3: 79 days
  City 4: 73 days
  City 5: 87 days


In [56]:
comfortable_mask = (daily_temps >= 15) & (daily_temps <= 25)
comfortable_days_per_city = np.sum(comfortable_mask, axis=0)
print(f"\nComfortable days (15-25°C) per city:")
for idx, count in enumerate(comfortable_days_per_city):
    print(f"  City {idx+1}: {count} days")



Comfortable days (15-25°C) per city:
  City 1: 67 days
  City 2: 82 days
  City 3: 83 days
  City 4: 77 days
  City 5: 72 days


In [57]:
temps_below_minus5 = np.sum(daily_temps < -5)
daily_temps[daily_temps < -5] = -5
print(f"\nData cleaning: Replaced {temps_below_minus5} values below -5°C with -5°C")



Data cleaning: Replaced 199 values below -5°C with -5°C


In [58]:
print("\n3. Fancy Indexing")
print("-" * 70)

specific_days = [0, 100, 200, 300, 364]
specific_days_temps = daily_temps[specific_days, :]
print(f"Temperatures on specific days {specific_days}:")
print(specific_days_temps)



3. Fancy Indexing
----------------------------------------------------------------------
Temperatures on specific days [0, 100, 200, 300, 364]:
[[ 8.72700594 37.53571532 26.59969709 19.93292421 -2.19906798]
 [24.9080857  16.80481832  5.47638081 30.68975099 24.23655863]
 [-0.74335356 17.09504737 33.64729179 26.61124432 30.32805739]
 [15.95408926 13.95909388 -5.          7.06239138  9.00978094]
 [ 0.28436311 -3.93067909 20.7506484  28.73168903 22.19521268]]


In [59]:
q1 = daily_temps[0:91, :].mean(axis=0)
q2 = daily_temps[91:182, :].mean(axis=0)
q3 = daily_temps[182:273, :].mean(axis=0)
q4 = daily_temps[273:365, :].mean(axis=0)

quarterly_avg = np.array([q1, q2, q3, q4])
print(f"\nQuarterly averages (4 quarters × 5 cities):")
print(quarterly_avg)
print(f"\nQuarter 1 avg: {q1}")
print(f"Quarter 2 avg: {q2}")
print(f"Quarter 3 avg: {q3}")
print(f"Quarter 4 avg: {q4}")



Quarterly averages (4 quarters × 5 cities):
[[15.662897   16.92730373 15.10955004 15.90890719 11.87218907]
 [15.28103689 14.71069816 13.28276485 15.21421182 14.38348045]
 [16.47446036 15.62081849 15.73777039 16.83902787 14.79792765]
 [14.26275419 14.63058699 15.60750721 13.20112908 16.87030399]]

Quarter 1 avg: [15.662897   16.92730373 15.10955004 15.90890719 11.87218907]
Quarter 2 avg: [15.28103689 14.71069816 13.28276485 15.21421182 14.38348045]
Quarter 3 avg: [16.47446036 15.62081849 15.73777039 16.83902787 14.79792765]
Quarter 4 avg: [14.26275419 14.63058699 15.60750721 13.20112908 16.87030399]


In [60]:
annual_avg = daily_temps.mean(axis=0)
sorted_indices = np.argsort(annual_avg)[::-1]
temps_sorted = daily_temps[:, sorted_indices]

print(f"\nCities rearranged by annual average (descending):")
print(f"Original annual averages: {annual_avg}")
print(f"Sorted indices: {sorted_indices}")
print(f"Sorted annual averages: {annual_avg[sorted_indices]}")



Cities rearranged by annual average (descending):
Original annual averages: [15.41711579 15.47004564 14.93624225 15.28509381 14.4875214 ]
Sorted indices: [1 0 3 2 4]
Sorted annual averages: [15.47004564 15.41711579 15.28509381 14.93624225 14.4875214 ]


In [62]:
print("\n1. Temperature Analysis")
print("-" * 70)

city_means = daily_temps.mean(axis=0)
city_medians = np.median(daily_temps, axis=0)
city_stds = daily_temps.std(axis=0)

print("Statistics for each city:")
for i in range(5):
    print(f"\nCity {i+1}:")
    print(f"  Mean: {city_means[i]:.2f}°C")
    print(f"  Median: {city_medians[i]:.2f}°C")
    print(f"  Std Dev: {city_stds[i]:.2f}°C")



1. Temperature Analysis
----------------------------------------------------------------------
Statistics for each city:

City 1:
  Mean: 15.42°C
  Median: 14.86°C
  Std Dev: 14.54°C

City 2:
  Mean: 15.47°C
  Median: 16.14°C
  Std Dev: 14.28°C

City 3:
  Mean: 14.94°C
  Median: 15.29°C
  Std Dev: 13.89°C

City 4:
  Mean: 15.29°C
  Median: 15.14°C
  Std Dev: 14.24°C

City 5:
  Mean: 14.49°C
  Median: 14.33°C
  Std Dev: 14.35°C


In [63]:
hottest_idx = np.unravel_index(daily_temps.argmax(), daily_temps.shape)
hottest_temp = daily_temps[hottest_idx]
print(f"\nHottest day of the year:")
print(f"  Day {hottest_idx[0]+1}, City {hottest_idx[1]+1}: {hottest_temp:.2f}°C")

coldest_idx = np.unravel_index(daily_temps.argmin(), daily_temps.shape)
coldest_temp = daily_temps[coldest_idx]
print(f"\nColdest day of the year:")
print(f"  Day {coldest_idx[0]+1}, City {coldest_idx[1]+1}: {coldest_temp:.2f}°C")



Hottest day of the year:
  Day 107, City 2: 39.99°C

Coldest day of the year:
  Day 2, City 2: -5.00°C


In [64]:
temp_ranges = daily_temps.max(axis=0) - daily_temps.min(axis=0)
print(f"\nTemperature range (max - min) for each city:")
for i, temp_range in enumerate(temp_ranges):
    print(f"  City {i+1}: {temp_range:.2f}°C")



Temperature range (max - min) for each city:
  City 1: 44.74°C
  City 2: 44.99°C
  City 3: 44.84°C
  City 4: 44.82°C
  City 5: 44.97°C


In [65]:
city_correlation = np.corrcoef(daily_temps.T)
print(f"\nCorrelation matrix between cities:")
print(city_correlation)
print("\nNote: Values close to 1 indicate strong positive correlation")



Correlation matrix between cities:
[[ 1.         -0.06127625  0.0164221   0.04605819  0.04298458]
 [-0.06127625  1.          0.08057526 -0.02906909 -0.00306557]
 [ 0.0164221   0.08057526  1.         -0.00439183 -0.01312075]
 [ 0.04605819 -0.02906909 -0.00439183  1.          0.09972553]
 [ 0.04298458 -0.00306557 -0.01312075  0.09972553  1.        ]]

Note: Values close to 1 indicate strong positive correlation


In [66]:
print("\n2. Sales Analysis")
print("-" * 70)

total_per_category = monthly_sales.sum(axis=0)
print("Total sales per product category:")
for i, total in enumerate(total_per_category):
    print(f"  Category {i+1}: ${total:,}")



2. Sales Analysis
----------------------------------------------------------------------
Total sales per product category:
  Category 1: $33,252
  Category 2: $36,747
  Category 3: $33,396
  Category 4: $39,039


In [67]:
avg_per_category = monthly_sales.mean(axis=0)
print("\nAverage monthly sales per category:")
for i, avg in enumerate(avg_per_category):
    print(f"  Category {i+1}: ${avg:.2f}")



Average monthly sales per category:
  Category 1: $2771.00
  Category 2: $3062.25
  Category 3: $2783.00
  Category 4: $3253.25


In [68]:
monthly_totals = monthly_sales.sum(axis=1)
best_month = monthly_totals.argmax()
months = ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
          'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec']
print(f"\nBest performing month overall:")
print(f"  {months[best_month]} with ${monthly_totals[best_month]:,}")



Best performing month overall:
  Dec with $15,252


In [69]:
best_category = total_per_category.argmax()
print(f"\nBest performing category overall:")
print(f"  Category {best_category+1} with ${total_per_category[best_category]:,}")



Best performing category overall:
  Category 4 with $39,039


In [70]:
print("\n3. Advanced Computations")
print("-" * 70)

window = 7
moving_avg = np.zeros((daily_temps.shape[0] - window + 1, daily_temps.shape[1]))

for city in range(daily_temps.shape[1]):
    moving_avg[:, city] = np.convolve(daily_temps[:, city],
                                       np.ones(window)/window,
                                       mode='valid')

print(f"7-day moving average shape: {moving_avg.shape}")
print(f"Sample moving average (first 5 days, City 1):")
print(moving_avg[:5, 0])



3. Advanced Computations
----------------------------------------------------------------------
7-day moving average shape: (359, 5)
Sample moving average (first 5 days, City 1):
[10.13223469 13.2312149  12.98867001 17.00668632 22.62225859]


In [71]:
z_scores = np.zeros_like(daily_temps)

for city in range(daily_temps.shape[1]):
    mean = daily_temps[:, city].mean()
    std = daily_temps[:, city].std()
    z_scores[:, city] = (daily_temps[:, city] - mean) / std

print(f"\nZ-scores computed for all cities")
print(f"Z-score mean (should be ~0): {z_scores.mean(axis=0)}")
print(f"Z-score std (should be ~1): {z_scores.std(axis=0)}")



Z-scores computed for all cities
Z-score mean (should be ~0): [-8.94261834e-17 -9.97679869e-17 -4.38005796e-17  1.42351884e-16
  6.99592591e-18]
Z-score std (should be ~1): [1. 1. 1. 1. 1.]


In [72]:
print("\nPercentiles (25th, 50th, 75th) for each city:")
for city in range(daily_temps.shape[1]):
    p25 = np.percentile(daily_temps[:, city], 25)
    p50 = np.percentile(daily_temps[:, city], 50)
    p75 = np.percentile(daily_temps[:, city], 75)
    iqr = p75 - p25

    print(f"\nCity {city+1}:")
    print(f"  25th percentile: {p25:.2f}°C")
    print(f"  50th percentile (median): {p50:.2f}°C")
    print(f"  75th percentile: {p75:.2f}°C")
    print(f"  IQR (75th - 25th): {iqr:.2f}°C")



Percentiles (25th, 50th, 75th) for each city:

City 1:
  25th percentile: 1.60°C
  50th percentile (median): 14.86°C
  75th percentile: 28.86°C
  IQR (75th - 25th): 27.26°C

City 2:
  25th percentile: 1.94°C
  50th percentile (median): 16.14°C
  75th percentile: 27.89°C
  IQR (75th - 25th): 25.95°C

City 3:
  25th percentile: 2.12°C
  50th percentile (median): 15.29°C
  75th percentile: 26.84°C
  IQR (75th - 25th): 24.72°C

City 4:
  25th percentile: 2.32°C
  50th percentile (median): 15.14°C
  75th percentile: 27.76°C
  IQR (75th - 25th): 25.44°C

City 5:
  25th percentile: 1.40°C
  50th percentile (median): 14.33°C
  75th percentile: 26.30°C
  IQR (75th - 25th): 24.91°C
